jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://${jdbc.host}:${jdbc.port}/${jdbc.database}?createDatabaseIfNotExist=true&characterEncoding=utf-8&useUnicode=true&zeroDateTimeBehavior=convertToNull
