connection:
  username: admin
  password: 123456
  remoteAddr: 127.0.0.1

  list:  #array list map 这种只能通过绑定到某个对象中然后再通过该对象获得,用@Value不行
    - ABC
    - DEF
    - EFG

  map:
    index1: value1
    index2: value2
    index3: value3

  array: 1,2,3,4

  listmap:
    - map1:
      index1: value1
      index2: value2
      index3: value3
    - map2:
      index1: value1
      index2: value2
      index3: value3

  str: dev

sample: abc